version: "3"

services:
  ui:
    ports:
      # We should use the same port internally and externally, otherwise the dev tools support
      # of the browser is for almost nothing
      - "8091:8091"
    command: yarn dev --host 0.0.0.0 --port 8091
    # command: bash -c 'while true; do sleep 5; done'
    restart: unless-stopped
    depends_on:
      - api
  api:
    environment:
      - DJANGO_DEBUG=True
      - DEV=True
    ports:
      - "5091:5000"
      - "8891:8888"
  db:
    ports:
      - "54391:5432"
