# Generated by Django 4.1.4 on 2023-01-06 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("SELECT create_hypertable('core_sensorreading', 'time');"),
        migrations.RunSQL(
            "ALTER TABLE core_sensorreading SET (timescaledb.compress, timescaledb.compress_segmentby = 'sensor_id');"
        ),
        migrations.RunSQL(
            "SELECT add_compression_policy('core_sensorreading', INTERVAL '7 days');"
        ),
    ]
