# Generated by Django 4.2.1 on 2023-05-17 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='measurement',
            unique_together={('time', 'entity', 'feature')},
        ),
        migrations.AlterIndexTogether(
            name='measurement',
            index_together={('time', 'entity', 'feature'), ('entity', 'feature')},
        ),
    ]
