# Generated by Django 4.1.5 on 2023-01-13 13:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_timescale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apexchart',
            name='sensors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='apexchart',
            name='switches',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, size=None),
        ),
    ]
