# Generated by Django 4.1.5 on 2023-01-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_timescale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApexConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('config', models.JSONField(null=True)),
            ],
        ),
    ]
