# Generated by Django 4.2.1 on 2023-05-22 06:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_measurement_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apexchart",
            name="switches",
        ),
        migrations.RemoveField(
            model_name="apexchart",
            name="yaxis_label",
        ),
        migrations.AddField(
            model_name="apexchart",
            name="yaxis_labels",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=50, null=True),
                blank=True,
                default="{}",
                size=None,
            ),
            preserve_default=False,
        ),
    ]
