# Generated by Django 4.1.5 on 2023-01-12 15:20

from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_apexconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apexconfig',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='apexconfig',
            name='config',
            field=django_jsonform.models.fields.JSONField(null=True),
        ),
    ]
