# Generated by Django 4.1.5 on 2023-01-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_config_apexchart_own_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='apexchart',
            name='xaxis_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apexchart',
            name='yaxis_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
