# Generated by Django 4.1.5 on 2023-01-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_apexchart_xaxis_label_apexchart_yaxis_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apexchart',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='apexchart',
            name='group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
