# Generated by Django 4.2.1 on 2023-05-16 09:52

import colorfield.fields
import django.contrib.postgres.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_apexchart_options_apexchart_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='apexchart',
            name='colors',
            field=django.contrib.postgres.fields.ArrayField(base_field=colorfield.fields.ColorField(default='#000', image_field=None, max_length=18, samples=None), default=['#000'], size=None),
            preserve_default=False,
        ),
    ]
