# Generated by Django 4.2.1 on 2023-05-16 09:53

import colorfield.fields
import django.contrib.postgres.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_apexchart_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apexchart',
            name='colors',
            field=django.contrib.postgres.fields.ArrayField(base_field=colorfield.fields.ColorField(blank=True, default='#000', image_field=None, max_length=18, samples=None), blank=True, size=None),
        ),
    ]
