# Generated by Django 4.2.1 on 2023-05-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_apexchart_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='apexchart',
            name='tickAmount',
            field=models.IntegerField(blank=True, default=6),
        ),
    ]
